[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "chii"
version = "0.0.4"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.10"
# dependencies
loguru = "==0.7.0"
SQLAlchemy = { extras = ["mypy", "asyncio"], version = "2.0.19" }
grpcio = "1.56.2"
grpcio-tools = "1.56.2"
libphpserialize = "0.0.8"
pymysql = "1.1.0"
pydantic = "2.0.2"
python-dotenv = "1.0.0"
etcd3-py = "0.1.6"
aiohttp = "3.8.5"
pydantic-settings = "2.0.1"
typing-extensions = '4.7.1'

[tool.poetry.group.dev.dependencies]
sqlacodegen = "2.3.0"
# tests
coverage = { version = "==7.2.7", extras = ["toml"] }
pytest = "==7.4.0"
pytest-cov = "4.1.0"
pytest-dotenv = "0.5.2"
pytest-github-actions-annotate-failures = "==0.2.0"
pytest-env = "==0.8.2"
# linter and formatter
pre-commit = "==3.3.3"
mypy = "==1.4.1"
watchgod = "0.8.2"
types-protobuf = "^4.21.0.2"

[tool.poetry-plugin-bump]
commit_msg = 'bump: v{version}'

[tool.coverage.run]
concurrency = ['thread', 'greenlet']

[tool.coverage.report]
exclude_lines = [
  'pragma: no cover',
  'if TYPE_CHECKING:',
  'if __name__ == "__main__":',
  'raise NotImplementedError'
]

[tool.pytest.ini_options]
addopts = '-rav'
env = ['D:TESTING=true', 'SQLALCHEMY_WARN_20=true']

[tool.mypy]
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
show_error_codes = true
pretty = true
plugins = ['sqlalchemy.ext.mypy.plugin', 'pydantic.mypy']

[tool.black]
target_version = ['py310']

extend-exclude="api/v1"

[tool.ruff]
extend-exclude = [".venv", "api"]

select = [
  "B",
  "C",
  "E",
  "F",
  "G",
  "I",
  "N",
  "Q",
  "S",
  "W",
  "BLE",
  #  "DJ",
  "ERA",
  "EXE",
  "ICN",
  "INP",
  "ISC",
  "NPY",
  #  "DTZ",
  #  "PTH",
  "PD",
  "PGH",
  "PIE",
  "PL",
  "PT",
  "PYI",
  "RET",
  "RSE",
  "RUF",
  "SIM",
  "SLF",
  "TCH",
  "TID",
  "TRY",
  "YTT",
]
ignore = [
  'N806',
  'N802',
  'N803',
  'E501',
  'BLE001',
  'RUF002',
  'S301',
  'S314',
  'S101',
  'N815',
  'S104',
  'C901',
  'ISC003',
  'PLR0913',
  'RUF001',
  'SIM108',
  'TCH003',
  'RUF003',
  'RET504',
  'TRY300',
  'TRY003',
  'TRY201',
  'TRY301',
  'PLR0912',
  'PLR0915',
  'PLR2004',
  'PGH003',
]

target-version = "py310"
