[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "chii"
version = "0.0.4"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.10"
# dependencies
pytz = "==2023.3"
loguru = "==0.7.0"
SQLAlchemy = { extras = ["mypy", "asyncio"], version = "2.0.12" }
grpcio = "1.54.0"
grpcio-tools = "1.54.0"
libphpserialize = "0.0.8"
pymysql = "1.0.3"
pydantic = "1.10.7"
python-dotenv = "1.0.0"
etcd3-py = "0.1.6"
aiohttp = "3.8.4"

[tool.poetry.group.dev.dependencies]
sqlacodegen = "2.3.0"
# tests
coverage = { version = "==7.2.5", extras = ["toml"] }
pytest = "==7.3.1"
pytest-dotenv = "0.5.2"
# linter and formatter
pre-commit = "==3.2.2"
flake8 = '6.0.0'
flake8-comprehensions = "==3.12.0"
flake8-bugbear = "==23.3.23"
flake8-pytest-style = "1.7.2"
flake8-pyproject = "1.2.3"
flake8-tidy-imports = "==4.8.0"
mypy = "==1.2.0"
requests = "==2.29.0"
types-pytz = "2023.3.0.0"
pytest-github-actions-annotate-failures = "==0.1.8"
pytest-env = "==0.8.1"
redis = { extras = ["hiredis"], version = "==4.5.4" }
watchgod = "0.8.2"
types-protobuf = "^4.21.0.2"
types-redis = "^4.3.21.7"

[tool.poetry-plugin-bump]
commit_msg = 'bump: v{version}'

[tool.coverage.run]
concurrency = ['thread', 'greenlet']

[tool.coverage.report]
exclude_lines = [
  'pragma: no cover',
  'if TYPE_CHECKING:',
  'if __name__ == "__main__":',
  'raise NotImplementedError'
]

[tool.pytest.ini_options]
addopts = '-rav -W error::sqlalchemy.exc.RemovedIn20Warning'
env = ['D:TESTING=true', 'SQLALCHEMY_WARN_20=true']

[tool.mypy]
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
show_error_codes = true
pretty = true
plugins = ['sqlalchemy.ext.mypy.plugin', 'pydantic.mypy']

[tool.black]
target_version = ['py310']


[tool.flake8]
max-line-length = 88
ignore = ['W503', 'B008', 'E203', 'E501']
exclude = ['.venv', '.git', '__pycache__', 'docs/source/conf.py', 'old', 'build', 'dist', 'tmp', 'api']
ban-relative-imports = 'parents'
