version: "3"

dotenv: [ .env ]

tasks:
  default:
    silent: true
    cmds:
      - task --list-all

  gen-grpc:
    desc: generate grpc python files
    generates:
      - ./api/**/*.py
    sources:
      - ./proto/**/*.proto
      - poetry.lock
    cmds:
      - >-
        poetry run python -m grpc_tools.protoc
        -I ./proto/
        --python_out=.
        --pyi_out=.
        --grpc_python_out=.
        ./proto/api/v1/timeline.proto

  gen-orm:
    desc: generate dataclasses from database
    dotenv:
      - .env
    cmds:
      - >-
        sqlacodegen --generator dataclasses
        --outfile chii/db/models.py
        --noviews
        'mysql+pymysql://{{.MYSQL_USER}}:{{.MYSQL_PASS}}@{{.MYSQL_HOST}}:{{.MYSQL_PORT}}/{{.MYSQL_DB}}'

  dev:
    dotenv:
      - .env
    sources:
      - '*.py'
      - 'chii/**.py'
      - 'rpc/**.py'
    generates:
      - a-file-not-exists-so-it-always-rerun
    cmd: python start_grpc_server.py

  mypy: mypy --show-column-numbers chii rpc

  lint:
    - poetry run ruff check .
    - poetry run mypy chii rpc
