version: "3"

dotenv: [ .env ]

tasks:
  default:
    silent: true
    cmds:
      - ruff check .
      - black .
      - mypy .

  gen-gql:
    desc: generate grpc python files
    generates:
      - ./api/**/*.py
    sources:
      - ./proto/**/*.proto
      - poetry.lock
    cmds:
      - >-
        datamodel-codegen
        --input gql/schema.graphql
        --input-file-type graphql
        --output gql/model.py
        --output-model-type dataclasses.dataclass
#        --use-standard-collections

  gen-grpc:
    desc: generate grpc python files
    generates:
      - ./api/**/*.py
    sources:
      - ./proto/**/*.proto
      - poetry.lock
    cmds:
      - >-
        poetry run python -m grpc_tools.protoc
        -I ./proto/
        --python_out=.
        --pyi_out=.
        --grpc_python_out=.
        ./proto/api/v1/timeline.proto

  gen-orm:
    desc: generate dataclasses from database
    dotenv:
      - .env
    cmds:
      - >-
        sqlacodegen --generator dataclasses
        --outfile chii/db/models.py
        --noviews
        'mysql+pymysql://{{.MYSQL_USER}}:{{.MYSQL_PASS}}@{{.MYSQL_HOST}}:{{.MYSQL_PORT}}/{{.MYSQL_DB}}'

  dev:
    dotenv:
      - .env
    sources:
      - '*.py'
      - 'chii/**/*.py'
      - 'rpc/**/*.py'
    generates:
      - a-file-not-exists-so-it-always-rerun
    cmd: python start_grpc_server.py

  graphql:
    dotenv:
      - .env
    sources:
      - '*.py'
      - 'chii/**/*.py'
      - 'rpc/**/*.py'
      - 'gql/**/*.py'
      - 'gql/**/*.graphql'
    generates:
      - a-file-not-exists-so-it-always-rerun
    cmds:
      - uvicorn gql.app:app

  mypy: mypy --show-column-numbers chii rpc

  lint:
    - poetry run ruff check .
    - poetry run mypy chii rpc
