# generated by datamodel-codegen:
#   filename:  schema.graphql
#   timestamp: 2024-09-27T16:44:53+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, TypeAlias

Boolean: TypeAlias = bool
"""
The `Boolean` scalar type represents `true` or `false`.
"""

Int: TypeAlias = int
"""
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.
"""

String: TypeAlias = str
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


@dataclass
class CollectTimeline:
    action: Int
    created_at: Int
    id: Int
    subject_id: List[Int]
    user_id: Int
