name: ci

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: git clone https://github.com/bangumi/dev-env $HOME/dev-env
      - run: cd ~/dev-env && docker-compose up -d

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: trim21/setup-poetry@dist/v1
      - uses: trim21/install-poetry-project@dist/v1

      - run: bash $HOME/dev-env/wait_mysql_ready.sh

      - run: pytest --cov
        timeout-minutes: 10
        env:
          MYSQL_HOST: '127.0.0.1'
          MYSQL_PORT: '3306'
          MYSQL_USER: 'user'
          MYSQL_PASS: 'password'
          MYSQL_DB: 'bangumi'

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: docker build -t base-image -f etc/base.dockerfile .
      - run: docker build -t tmp -f etc/final.dockerfile .
      - run: docker run tmp --help
