name: autofix.ci

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - uses: astral-sh/setup-uv@v5
      - run: uv sync --frozen

      - run: echo ".venv/bin/" >> $GITHUB_PATH

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: task gen-grpc

      - uses: autofix-ci/action@v1.3.1
        with:
          fail-fast: false
