name: autofix.ci

on:
  push:
    branches-ignore:
      - renovate/**
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: trim21/setup-poetry@dist/v2
      - uses: trim21/install-poetry-project@dist/v2
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: task gen-grpc

      - uses: autofix-ci/action@v1.3.1
        with:
          fail-fast: false
