name: lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - uses: astral-sh/setup-uv@v5
      - run: uv sync --frozen

      - uses: liskin/gh-problem-matcher-wrap@v3
        with:
          action: add
          linters: mypy

      - name: mypy
        run: uv run mypy --show-column-numbers .

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - run: pip install pre-commit

      - uses: trim21/actions/pre-commit@master
