name: lint

on:
  push:
    branches-ignore:
      - renovate/**
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: Trim21/setup-poetry@dist/v2

      - uses: Trim21/install-poetry-project@dist/v2

      - uses: liskin/gh-problem-matcher-wrap@v3
        with:
          action: add
          linters: mypy
          run: ''

      - name: mypy
        run: mypy --show-column-numbers chii rpc

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: trim21/setup-poetry@dist/v2
      - uses: trim21/install-poetry-project@dist/v2
      - uses: trim21/actions/pre-commit@master
