name: Release(Docker)

on:
  push:
    tags:
      - v*
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE: 'ghcr.io/${{ github.repository_owner }}/ms-timeline'

    concurrency:
      group: ${{ github.workflow }}-${{ github.sha }}
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=semver,pattern=v{{version}}

            type=ref,event=branch
            type=ref,event=branch,suffix=-{{ sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://docs.docker.com/build/ci/github-actions/cache/#cache-mounts
      - name: Go Build Cache for Docker
        uses: actions/cache@v4
        with:
          path: pip-wheel-cache
          key: ${{ runner.os }}-pip-cache-${{ hashFiles('**/poetry.lock') }}
          restore-keys:
            ${{ runner.os }}-pip-cache-

      - name: inject pip-wheel-cache into docker
        uses: reproducible-containers/buildkit-cache-dance@v3.1.2
        with:
          cache-map: |
            {
              "pip-wheel-cache": "/root/.cache/pip"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Build Final Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./
          provenance: false
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          github-token: ${{ github.token }}
