name: release

on:
  push:
    tags:
      - v*
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE: "ghcr.io/${{ github.repository_owner }}/ms-timeline"

    concurrency:
      group: release-docker
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - run: |
          export "TAG_HASH=1-${HASH_POETRY_LOCK:0:10}-${HASH_BASE_DOCKER:0:10}"

          if ! docker pull "${IMAGE}:base-${TAG_HASH}"; then
            echo "build base docker image"
            docker build -t "${IMAGE}:base-${TAG_HASH}" -f etc/base.dockerfile .
            docker push "${IMAGE}:base-${TAG_HASH}"
          fi

          docker tag "${IMAGE}:base-${TAG_HASH}" base-image

        env:
          HASH_POETRY_LOCK: "${{ hashFiles('poetry.lock') }}"
          HASH_BASE_DOCKER: "${{ hashFiles('etc/base.dockerfile') }}"
        name: build base docker image

      - run: |
          echo "TAG=master-$(git describe --match='v*' --tags)" >> $GITHUB_ENV
          echo "REF=master" >> $GITHUB_ENV
        if: "${{ !startsWith(github.ref, 'refs/tags/') }}"

      - run: |
          echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "REF=latest" >> $GITHUB_ENV
        if: "${{ startsWith(github.ref, 'refs/tags/') }}"

      - name: docker build
        run: docker build --build-arg "ARG_REF=${TAG}" -t current -f etc/main.dockerfile .

      - name: push tags
        run: |
          docker tag current "${IMAGE}:${REF}"
          docker push "${IMAGE}:${REF}"

          docker tag current "${IMAGE}:${TAG}"
          docker push "${IMAGE}:${TAG}"
